language: php

php:
  - 5.6
  - hhvm
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer require satooshi/php-coveralls:dev-master
  - composer install --dev

script:
  - ./vendor/bin/phpunit  --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
