language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

before_script:
  - composer install

script: php -d zend_extension=xdebug.so -d xdebug.max_nesting_level=300 -d xdebug.coverage_enable=On ./vendor/bin/phpunit  --coverage-text --colors=never tests
