language: php

php:
  - 5.6
  - hhvm
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install --dev

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
